### ISSUE TITLE
Node 14.x / ES6 Support

### ISSUE THREAD

**Issue by NickLiffen** [EliLillyCo/github-actions-post-to-pr#8]
Hey @lilly-nathanamorin 👋 

Can you assign this story to me and I will try and get around to it after current workload calms down:

- `CHANGELOG.md` creation.
- Move support to imports vs require. 
- ES6 Support Throughout.
- Update README.md with a Contribution section. 

Thanks mate! 

Is there anything else you think needs doing?

**Comment by lilly-nathanamorin** [comment]
These look great, thanks!
